# Usar imagen oficial de Python 3.10
FROM python:3.10-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar archivo de requerimientos
COPY api/requirements.txt ./

# Instalar dependencias del sistema 
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código de la aplicación
COPY api/ .

# Establecer variables de entorno
ENV FLASK_APP=app.py
ENV FLASK_ENV=development

# Exponer el puerto en el que corre la aplicación
EXPOSE 5000

# Ejecutar la aplicación
CMD ["flask", "run", "--host=0.0.0.0"]